[package]
name = "eztrans-rs"
version = "0.1.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2018"
license = "GPL-3.0"

[features]
default = []

[dependencies]
libc = "0.2.65"
dlopen = "0.1.8"
dlopen_derive = "0.1.4"

